version: '3.5'

services:

  postgres:
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: 'postgres:12.4'
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - "0.0.0.0:6379:6379"
    volumes:
      - 'redisdata:/data'
  web:
    build: .
    depends_on:
      - postgres
      - redis
    expose:
      - 8000
    env_file:
      - ./.env
    command: /bin/sh -c 'python -m scripts.migrate';'python -m task_manager.main';
    volumes:
      - ./prototype:/code/prototype

volumes:
  pgdata:
  redisdata:


# python -m instead_of_ml.main && python -m responder.main