version: '3.4'

services:

  postgres:
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: 'postgres:12.4'
    ports:
      - '0.0.0.0:5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'

  redis:
    container_name: 'redis'
    image: 'redis:3.2.0'
    ports:
      - '0.0.0.0:6379:6379'
    volumes:
      - 'redisdata:/data'
  web:
    build: .
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      - BOT_TOKEN=5134459296:AAGKH7IaGN_Pupq_xVnmoKH-ShzmsTe_A5w
      - PG_DATABASE_URL=postgres://postgres:postgres@0.0.0.0/postgres
      - REDIS_URL=redis://0.0.0.0
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=reddis
    command: /bin/sh -c 'python -m scripts.migrate';
    volumes:
      - ./prototype:/code/prototype

volumes:
  pgdata:
  redisdata:
